### ISSUE TITLE
Error when installing on a Teltonika rutx08

### ISSUE THREAD

**Issue by Andi-bz** [messense/openwrt-netbird#34] opened 2022-11-05 16:41 UTC
Hi,

When I install this package, I get this error:

`root@Router:~# opkg install netbird_10.4-1_arm_cortex-a7_neon-vfpv4.ipk
Upgrading netbird on root from 0.10.1-1 to 0.10.4-1...
Configuring netbird.
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a7_neon-vfpv4/vuci). Skipping.`

CPU: Quad-core ARM Cortex A7, 717 MHz
Package: netbird_0.10.4-1_arm_cortex-a7_neon-vfpv4.ipk

If I remove the last line of /etc/opkg/distfeeds.conf it works, but I get the following error when running it:

Error relocating /usr/bin/netbird: __nanosleep_time64: symbol not found

**Comment by messense** [comment] 2022-11-17 03:38
Duplicate of #6

**Closed by messense** 2022-11-17 03:38 UTC
Labels: duplicate
